import 'dart:convert';
import 'dart:typed_data';

// ============================================================
// VEIL CODEC — string-hiding codec (template default: position-XOR)
// ============================================================
// Every "veiled" byte array in this project is decoded through this
// file. The bytes at rest in the compiled binary are NEVER the
// plaintext; they only become the plaintext after passing through
// [reveal].
//
// ─────────────────────────────────────────────────────────────
// WHY THIS FILE IS ONE OF FIVE INTERCHANGEABLE CODECS
// ─────────────────────────────────────────────────────────────
// Store scanners cluster apps by the SHAPE of the decoder loop, not
// only by the encoded bytes themselves. Two apps sharing the same
// KSA/PRGA loop are grouped even when their salts differ. To defeat
// that, `tool/forge/` ships a registry of five entirely different
// codec families:
//
//   1. position-xor      — this file (template default)
//   2. fnv-lcg-stream    — FNV-1a seeded xorshift keystream
//   3. rc4-ksa-prga      — RC4-style permutation
//   4. table-permutation — fixed 256-byte lookup swap
//   5. base64-mask       — Base64 → per-byte XOR against a mask key
//
// The forge tool picks ONE family per project (never the same as the
// previous project) and rewrites this file from
// `tool/forge/codecs/<family>.dart.tpl`. The public API stays the
// same — a single `String reveal(List<int>)` function — so the rest
// of the codebase never changes.
//
// ─────────────────────────────────────────────────────────────
// PUBLIC API CONTRACT
// ─────────────────────────────────────────────────────────────
//   - `String reveal(List<int> encoded)` : decode an encoded array.
//   - Empty input returns "". This is the safe path the template
//     takes while `veiled_bytes.dart` still holds empty defaults.
//
// The encoding twin (a `List<int> conceal(String)`) lives in
// `tool/forge/mint.dart` and MUST use the same algorithm + salt.
//
// ─────────────────────────────────────────────────────────────
// [FORGE] MANDATORY per-project change
// ─────────────────────────────────────────────────────────────
// Never ship two projects with the same combination of algorithm
// family + salt bytes + stream length. `dart run tool/forge/mint.dart`
// enforces this against the portfolio registry.
//
// Rotate ALL of:
//   • The active codec file (this file is one of five)
//   • `_saltBytes`   — 12–24 random bytes unique to this project
//   • `_streamLen`   — an int in [16..48] outside sibling values
// ============================================================

// [FORGE] Random salt bytes. Regenerated by the forge tool.
const List<int> _saltBytes = <int>[
  0x2F, 0x91, 0xC4, 0x1D, 0x77, 0xAA, 0x53, 0xB6,
  0x08, 0xE2, 0x39, 0x84, 0x5C, 0xF1, 0x6B, 0x22,
];

// [FORGE] Keystream length in bytes. Rotate per project (16..48).
const int _streamLen = 22;

// ─────────────────────────────────────────────────────────────
// Algorithm — POSITION-XOR (template default)
// ─────────────────────────────────────────────────────────────
// 1. Fold [_saltBytes] into a 32-bit accumulator using a Weyl-style
//    additive step (deterministic, no multiplication overflow on 32-bit
//    Web platforms).
// 2. Seed a xorshift32 generator; harvest the high byte of each state
//    into a fresh keystream of length [_streamLen].
// 3. For each input byte at position i:
//      plain[i] = (encoded[i] XOR keystream[i % len] XOR positionMask(i)) & 0xFF
//    where positionMask(i) mixes the low byte of i with a Weyl step so
//    identical plaintext bytes never encode identically.
// ─────────────────────────────────────────────────────────────

const int _weylStep = 0x9E3779B1;

Uint8List _keystream() {
  int accumulator = 0x243F6A88;
  for (int i = 0; i < _saltBytes.length; i++) {
    accumulator = (accumulator + _saltBytes[i] * (i + 1) + _weylStep) &
        0xFFFFFFFF;
  }
  int state = accumulator == 0 ? _weylStep : accumulator;
  final Uint8List stream = Uint8List(_streamLen);
  for (int i = 0; i < _streamLen; i++) {
    state ^= (state << 13) & 0xFFFFFFFF;
    state ^= state >> 17;
    state ^= (state << 5) & 0xFFFFFFFF;
    state &= 0xFFFFFFFF;
    stream[i] = (state >> 16) & 0xFF;
  }
  return stream;
}

final Uint8List _stream = _keystream();

int _positionMask(int i) => ((i * _weylStep) >> 16) & 0xFF;

/// Reveals the plaintext behind an encoded byte list.
///
/// Returns `""` for an empty input — that is the state on a fresh
/// template checkout, before the forge tool has been run. Callers
/// that must know whether a value is "not configured yet" MUST check
/// `.isEmpty` on the returned string, not the input.
String reveal(List<int> encoded) {
  if (encoded.isEmpty) return '';
  final Uint8List out = Uint8List(encoded.length);
  for (int i = 0; i < encoded.length; i++) {
    out[i] = (encoded[i] ^ _stream[i % _streamLen] ^ _positionMask(i)) & 0xFF;
  }
  return utf8.decode(out);
}
